# Base image with necessary dependencies
FROM python:3.12

# Set working directory
WORKDIR /app

# Copy and install requirements for each Python application
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install requests

# Copy application files for each Python application
COPY QoSManager.py .
COPY models .
CMD ["python", "QoSManager.py"]
