FROM nginx:latest

# Install Lua and required packages
RUN apt-get update \
    && apt-get install -y lua5.3 libnginx-mod-http-lua && \
    rm -rf /var/lib/apt/lists/*

# Copy Nginx configuration file and Lua script
COPY nginx.conf /etc/nginx/nginx.conf
COPY lua-scripts/ /etc/nginx/lua-scripts/

# Expose port
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
