FROM openresty/openresty:latest

# Set the user to "nginx"
RUN useradd -r nginx


# Copy your Nginx configuration and Lua scripts
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY lua-scripts /usr/local/openresty/nginx/lua-scripts
# CMD to start Nginx in the foreground
CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
