FROM openresty/openresty:latest

# Install MySQL client library
RUN apt-get update \
    && apt-get install -y default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Create a directory for Lua scripts
RUN mkdir /usr/local/openresty/nginx/lua-scripts
COPY mime.types /etc/nginx/mime.types
# Copy Lua script and Nginx configuration
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

# Set the working directory
WORKDIR /usr/local/openresty/nginx
