version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
        - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
  
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3307"
  
  filesystem:
    build:
      context: ./filesystem
      dockerfile: Dockerfile.scripts
    depends_on:
      - zookeeper
      - broker
    volumes: 
      - ./filesystem:/app/filesystem
  
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile.scripts
    depends_on:
      - zookeeper
      - broker
      - db
    volumes: 
      - ./manager:/app/manager
  
  controller_manager:
    build:
      context: ./controller_manager
      dockerfile: Dockerfile.scripts
    depends_on:
      - zookeeper
      - broker
      - db
    volumes: 
      - ./controller_manager:/app/controller_manager
  
  download_controller:
    build:
      context: ./download_controller
      dockerfile: Dockerfile.scripts
    depends_on:
      - zookeeper
      - broker
      - db
    volumes: 
      - ./download_controller:/app/download_controller
  
  uploadcontroller:
    build:
      context: ./uploadcontroller
      dockerfile: Dockerfile.scripts
    depends_on:
      - zookeeper
      - broker
      - db
    volumes: 
      - ./uploadcontroller:/app/uploadcontroller