apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesystem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filesystem
  template:
    metadata:
      labels:
        app: filesystem
    spec:
      containers:
      - name: filesystem-container
        image: python:3.12
        workingDir: /app
        command: ["python", "fileSystem.py"]
        ports:
        - containerPort: 80  # Adjust the port if needed
        volumeMounts:
        - name: filesystem-files
          mountPath: /app
      volumes:
      - name: filesystem-files
        configMap:
          name: filesystem-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: filesystem-configmap
data:
  filesystem.py: |
    {{ .Files.Get "fileSystem.py" | indent 4 }}
  requirements.txt: |
    {{ .Files.Get "requirements.txt" | indent 4 }}
  templates: | 
    {{ .Files.Get "templates" | indent 4 }}
---

apiVersion: v1
kind: Service
metadata:
  name: filesystem-service
spec:
  selector:
    app: filesystem
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Should match the container port in Deployment
  type: ClusterIP