apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: distribuitedfilesystem-nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

#      networks:
#      - vpcbr
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default  # Adjust the namespace as needed
spec:
  rules:
  - host: 0.0.0.0.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 8080  # Use the NodePort allocated to your Nginx service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: distribuitedfilesystem-db:latest
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: giovanni
        - name: MYSQL_DATABASE
          value: ds_filesystem
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: user
        ports:
        - containerPort: 3306
  #       volumeMounts:
  #       - name: mysql-persistent-storage
  #         mountPath: /var/lib/mysql
  # volumes:
  # - name: mysql-persistent-storage
  #   persistentVolumeClaim:
  #     claimName: mysql-pv-claim
#      volumes:
#     r - name: mysql-data
#        hostPath:
#          path: /path/to/mysql-data
#      - name: mysql-logs
#        hostPath:
#          path: /path/to/mysql-logs
#      networks:
#      - vpcb
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
        - containerPort: 2181
#      networks:
#      - vpcbr
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        - containerPort: 9093

        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://kafka-service:9093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "INSIDE://0.0.0.0:9093"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"


---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /your/preferred/path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: kafka
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesystem-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filesystem
  template:
    metadata:
      labels:
        app: filesystem
    spec:
      containers:
      - name: filesystem
        image: distribuitedfilesystem-filesystem1:latest
        imagePullPolicy: Never

#        volumes:
#        - name: filesystem
#          hostPath:
#            path: /path/to/filesystem
#      networks:
#      - vpcbr
---
apiVersion: v1
kind: Service
metadata:
  name: filesystem-service
spec:
  selector:
    app: filesystem
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: distribuitedfilesystem-manager:latest
        imagePullPolicy: Never

#        volumes:
#        - name: manager
#          hostPath:
#            path: /path/to/manager
#      networks:
#      - vpcbr

---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
spec:
  selector:
    app: manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controllermanager
  template:
    metadata:
      labels:
        app: controllermanager
    spec:
      containers:
      - name: controllermanager
        image: distribuitedfilesystem-controller_manager:latest
        imagePullPolicy: Never

#        volumes:
#        - name: controller_manager
#          hostPath:
#            path: /path/to/controller_manager
#      networks:
#      - vpcbr
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
spec:
  selector:
    app: controllermanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-controller-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: downloadcontroller
  template:
    metadata:
      labels:
        app: downloadcontroller
    spec:
      containers:
      - name: downloadcontroller
        image: distribuitedfilesystem-download_controller1:latest
        imagePullPolicy: Never
---
#        volumes:
#        - name: download_controller1
#          hostPath:
#            path: /path/to/download_controller1
#      networks:
#      - vpcbr


#        volumes:
#        - name: download_controller2
#          hostPath:
#            path: /path/to/download_controller2
#      networks:
#      - vpcbr

---
apiVersion: v1
kind: Service
metadata:
  name: download-controller-service
spec:
  selector:
    app: downloadcontroller  # Common label selector for both download_controller1 and download_controller2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploadcontroller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploadcontroller
  template:
    metadata:
      labels:
        app: uploadcontroller
    spec:
      containers:
      - name: uploadcontroller
        image: distribuitedfilesystem-uploadcontroller:latest
        imagePullPolicy: Never


---
apiVersion: v1
kind: Service
metadata:
  name: uploadcontroller-service
spec:
  selector:
    app: uploadcontroller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: updatecontroller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: updatecontroller
  template:
    metadata:
      labels:
        app: updatecontroller
    spec:
      containers:
      - name: updatecontroller
        image: distribuitedfilesystem-updatecontroller:latest
        imagePullPolicy: Never


---
apiVersion: v1
kind: Service
metadata:
  name: updatecontroller-service
spec:
  selector:
    app: updatecontroller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

