apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: distribuitedfilesystem-manager:latest
        imagePullPolicy: Never


---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
spec:
  selector:
    app: manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP