apiVersion: apps/v1
kind: Deployment
metadata:
  name: qosmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qosmanager
  template:
    metadata:
      labels:
        app: qosmanager
    spec:
      containers:
      - name: qosmanager
        image: distribuitedfilesystem-qosmanager:latest
        imagePullPolicy: Never
      serviceAccountName: deployment-manager
---

apiVersion: v1
kind: Service
metadata:
  name: qosmanager-service
spec:
  selector:
    app: qosmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

  ---
  apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-manager
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-manager
  namespace: default
subjects:
- kind: ServiceAccount
  name: deployment-manager # Name of the ServiceAccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io