apiVersion: apps/v1
kind: Deployment
metadata:
  name: updatecontroller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: updatecontroller
  template:
    metadata:
      labels:
        app: updatecontroller
    spec:
      containers:
      - name: updatecontroller
        image: distribuitedfilesystem-updatecontroller:latest
        imagePullPolicy: Never


---
apiVersion: v1
kind: Service
metadata:
  name: updatecontroller-service
spec:
  selector:
    app: updatecontroller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP