apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploadcontroller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploadcontroller
  template:
    metadata:
      labels:
        app: uploadcontroller
    spec:
      containers:
      - name: uploadcontroller
        image: distribuitedfilesystem-uploadcontroller:latest
        imagePullPolicy: Never


---
apiVersion: v1
kind: Service
metadata:
  name: uploadcontroller-service
spec:
  selector:
    app: uploadcontroller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP