version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    container_name: sender
    ports:
      - "5000:5000"
    environment:
      - SENDER=sender.py
    
  prometheus-scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: prometheus-scraper
    depends_on:
      - prometheus