version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  webapp:
    image: nginx
    container_name: webapp
    ports:
      - "80:80"
  
  sender:
    image: python:latest
    container_name: sender
    volumes:
      - ./sender.py:/sender.py
    command: ["python", "/sender.py"]