version: '3'
services:
  nginx:
    build: .
    ports:
      - "8080:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: giovanni
      MYSQL_DATABASE: ds_filesystem
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    hostname: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1